export const GET_VAULTS_REQUEST = 'GET_VAULTS_REQUEST';
export const GET_VAULTS_SUCCESS = 'GET_VAULTS_SUCCESS';
export const GET_VAULTS_FAILURE = 'GET_VAULTS_FAILURE';

export const CREATE_VAULT_REQUEST = 'CREATE_VAULT_REQUEST';
export const CREATE_VAULT_SUCCESS = 'CREATE_VAULT_SUCCESS';
export const CREATE_VAULT_FAILURE = 'CREATE_VAULT_FAILURE';

export const GET_ALL_FOLDERS_REQUEST = 'GET_ALL_FOLDERS_REQUEST';
export const GET_ALL_FOLDERS_SUCCESS = 'GET_ALL_FOLDERS_SUCCESS';
export const GET_ALL_FOLDERS_FAILURE = 'GET_ALL_FOLDERS_FAILURE';

export const UPDATE_VAULT_REQUEST = 'UPDATE_VAULT_REQUEST';
export const UPDATE_VAULT_SUCCESS = 'UPDATE_VAULT_SUCCESS';
export const UPDATE_VAULT_FAILURE = 'UPDATE_VAULT_FAILURE';

export const DELETE_VAULT_REQUEST = 'DELETE_VAULT_REQUEST';
export const DELETE_VAULT_SUCCESS = 'DELETE_VAULT_SUCCESS';
export const DELETE_VAULT_FAILURE = 'DELETE_VAULT_FAILURE';

export const GET_VAULT_BY_ID_REQUEST = 'GET_VAULT_BY_ID_REQUEST';
export const GET_VAULT_BY_ID_SUCCESS = 'GET_VAULT_BY_ID_SUCCESS';
export const GET_VAULT_BY_ID_FAILURE = 'GET_VAULT_BY_ID_FAILURE';
